### ISSUE TITLE
Link directly to mix tasks in sidebar

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ex_doc#1051]
Since mix tasks do not seem to have any subsections except for Top it is unnecessary to show it and we should instead link directly to the task.

![image](https://user-images.githubusercontent.com/316890/61381768-d9e44300-a8ab-11e9-9961-75f2afa9efb9.png)

**Comment by wojtekmach** [comment]
This came up many times, and I believe the consensus was, and that's what we do now, is to show a little arrow icon whenever you hover over a sidebar link, if you click that arrow you'd go directly to the page instead of expanding. That being said, personally, I would be ok with not showing the subsections in cases like this one.

**Comment by ericmj** [comment]
Do you have the links to the other discussions. I don't see a reason for the extra click since I only have one choice after clicking the task.

**Comment by josevalim** [comment]
If we make some of them automatically redirect, then it is confusing because the user may be expecting only to navigate the menu and now they moved away. And that would happprn only in certain cases. Plus some mix talks have functions, such as the profile ones.

**Comment by ericmj** [comment]
Aha, didn't realize some tasks have public functions.
