### ISSUE TITLE
Allow doctest in extra markdown pages

### ISSUE THREAD

**Issue by sezaru** [elixir-lang/ex_doc#1136]
Is it possible to enable doctest to work with extra markdown pages?

Possible scenario:
I create a new page.md that I add as part of my `:extras` parameter, this page is a "cookbook" that will give an overall example of the app/library, this means that it will have a lot of code, it would be great if this code could be doctested too to avoid it becoming outdated.

**Comment by josevalim** [comment]
Right now it is not possible and we don't have plans for it. But you can always parse the Elixir code in there yourself and use the functions in the `Code` module to evaluate the code and what not.

That will probably work better than doctests anyway, because in a cookbook you often need to test one snippet after the other, while doctest would run each snippet in isolation.
