### ISSUE TITLE
Thougths about Earmark

### ISSUE THREAD

**Issue by RobertDober** [elixir-lang/ex_doc#1142]
@josevalim @wojtekmach 
Given that you already use `as_ast` and that I am working on the Transformer for Earmark 1.5 (which is buggy in 1.4) I was thinking that maybe the time is come to split Earmark into two libraries.

I have already discussed this with @pragdave a long time ago concerning the command line tool which is imported by thousands of Elixir projects without any need indirectly by `ex_doc`.

If you plan to use only `as_ast` I could remove the html transformation and the CLI from Earmark, let' say 1.6 (or 2.0?) all together, than putting `ex_doc` into your mix.exs will only load the part of Earmark that is really needed.

I will then release seperate `EarmarkCLI` and `EarmarkTransform` libraries.

BTW if in the future maintaining your transformer might turn out too costly be assured that the `EarmarkTransform` lib will take `ex_doc` as serious as `Earmark` does today.

Thank you for your thoughts on that idea.

**Comment by RobertDober** [comment]
Oh and BTW if you want to release the internal transformer as a separate lib I would not be offended either ;). But it would be good not to do the same work twice maybe.

**Comment by josevalim** [comment]
Hi @RobertDober! Thanks for pinging me!

I think it is well decided we will be using only `as_ast`. However, in my opinion, it is not necessary to split the library. Most of the work is the AST handling. If you move the CLI, would we save what? 200 LOC for the CLI and 300 LOC for the HTML transformer? At the large scale of things, it is not really relevant. Especially because splitting it apart would most likely increase your burden as a maintainer.

My $.02. :) Have a good weekend!
