### ISSUE TITLE
ex_doc <-> boundary integrations

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-lang/ex_doc#1258]
I'm looking into ways of integrating `Boundary` data into ex_doc generated documentation and I'm wondering if there's an existing best practice to do something like that? I would imagine ex_doc does not necessarily want to depend on each and every third party wanting to provide additional documentation.

Sadly it seems the problem can't be (easily?) solved by using documentation metadata, as `Boundary` runs at compilation time aggregating results only after compilation is finished. At least I'm not aware how it could provide documentation metadata after the fact.

**Comment by LostKobrakai** [comment]
Additional context can be found here: https://github.com/sasa1977/boundary/pull/21

**Comment by josevalim** [comment]
I will be honest and say that we currently don't have bandwidth or time to consider nor implement this. Our medium-to-long term focus right now is on Erlang integration so if someone can work out the details and submit a proposal, then that would be great, otherwise we will probably shelve this until our on going work is completed.

**Comment by LostKobrakai** [comment]
That's perfectly fine. I was mostly wondering if there might be already things existing or planed. Sounds like it's best to revisit this at a later time.
