### ISSUE TITLE
Mix commands in reference links do not work

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1343]
This works.
```markdown
[`ecto.gen.migration`](`mix ecto.gen.migration`)
```

And this does not.

```markdown
[`ecto.gen.migration`]

...

[`ecto.gen.migration`]: `mix ecto.gen.migration`
```

**Comment by wojtekmach** [comment]
Given that our references like `` `foo` `` are in a way our extension to Markdown, I think it is understandable that it doesn't necessarily work everywhere. Given the fix is trivial

```diff
- [`ecto.gen.migration`]
+ [`mix ecto.gen.migration`]
```

(sure, we don't have our custom link text but in this case I'd say the custom one is worse)

I'm inclined to leave this unresolved, but of course feel free to pursue it if you want.

**Comment by josevalim** [comment]
It should definitely require the mix explicit. That's the rule.
