### ISSUE TITLE
callbacks implementations are not listed in the module if `@impl true`

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1352]
Given the following example.

```elixir
defmodule SomeCallback do
  @doc """
  My documentation here
  """
  @callback something() :: keyword()
end


defmodule ImplTrue do
  @behaviour SomeCallback

  @impl true
  def something() do
    [a: "apple"]
  end

  @doc "bar..."
  def bar(), do: :ok
end


defmodule NoImpl do
  @behaviour SomeCallback

  def something() do
    [a: "apple"]
  end

  @doc "bar..."
  def bar(), do: :ok
end
```

`mix docs` for `ImplTrue` will not list `something/1`, while for `NoImpl` it shows the function.
Originally reported by vrod in https://elixirforum.com/t/documentation-for-callback/38758

**Comment by eksperimental** [comment]
I see it is not an ExDoc issue, it is rather coming from Elixir itself.
```elixir
iex(2)> Code.fetch_docs(NoImpl)      
{:docs_v1, 22, :elixir, "text/markdown", %{}, %{},
 [
   {{:function, :bar, 0}, 29, ["bar()"], %{"en" => "bar..."}, %{}},
   {{:function, :something, 0}, 25, ["something()"], %{}, %{}}
 ]}
iex(3)> Code.fetch_docs(ImplTrue)
{:docs_v1, 9, :elixir, "text/markdown", %{}, %{},
 [
   {{:function, :bar, 0}, 17, ["bar()"], %{"en" => "bar..."}, %{}},
   {{:function, :something, 0}, 13, ["something()"], :hidden, %{}}
 ]} 
```

I see where this is coming from.
https://github.com/elixir-lang/elixir/blob/09896a609fa552feeabc53506df846c4ff7bb05b/lib/elixir/lib/module.ex#L1489-L1522

Any specific reason why doing `doc = if is_nil(doc) && impl, do: false, else: doc`?

**Comment by josevalim** [comment]
Yes, that’s by design and the docs for @impl mention so. After all, you don’t want to export GenServer callbacks and so on.

**Comment by eksperimental** [comment]
> Yes, that’s by design and the docs for @impl mention so. After all, you don’t want to export GenServer callbacks and so on.

Yes, I missed that last sentence in the docs for @impl

It makes sense... now my question is, shouldn't we be consitent and set `@doc false` for callback implementation that do not set `@impl` for the very same reason? after all `@impl` is an optional attribute to aid the user read the code.

**Comment by josevalim** [comment]
The goal was to not make this decision implicitly for the user but I believe ExDoc could not show docs for `@callback` by default. WDYT?

**Comment by wojtekmach** [comment]
+1

**Comment by eksperimental** [comment]
> The goal was to not make this decision implicitly for the user but I believe ExDoc could not show docs for `@callback` by default. WDYT?

Sorry, I don't fully understand what you mean. 
Which way should we take?

**Comment by josevalim** [comment]
I mean that if the goal is consistency, we should not show docs for callbacks in ExDoc, unless they are explicitly given.

**Comment by wojtekmach** [comment]
Just for some extra context, we initially implemented the feature in https://github.com/elixir-lang/ex_doc/pull/641.

We later revised it in https://github.com/elixir-lang/ex_doc/pull/1094. Instead of copying the callback docs, we now emit docs that contain a link to the callback docs. Worth repeating the example from #1094. If you have an app with an Ecto repo, today the repo will be documented like this:

<img width="475" alt="image" src="https://user-images.githubusercontent.com/76071/127638929-b7997360-72c1-4b4f-8407-22e66205988a.png">

And that is precisely because `use Ecto.Repo` does _not_ set `@impl true`.

Now we want to drop that functionality. We'd only show docs for callbacks if you explicitly do `@doc ...` for that callback. I'm again fine with that. I just want to double-check that we want to move forward with it given the extra context that was perhaps easy to miss. WDYT @josevalim?

**Comment by josevalim** [comment]
Let’s keep things as is. There is a clear track to why we arrived to the current status.

**Comment by josevalim** [comment]
If you don’t want to show it, @impl true it.
