### ISSUE TITLE
Default to preview.hex.pm on the current version as source location 

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#1368]

**Comment by mgibowski** [comment]
I see two issues about it:

1. Currently, preview.hex.pm is missing core elixir packages (`eex elixir ex_unit iex logger mix hex`)
2. Landing on GitHub makes it very easy to introduce quick simple changes to documentation. Since some time you can "suggest an edit" to any file - user clicks and edit button and GitHub automatically creates a fork without leaving their UI.

I guess the first one could be easily fixed. The second point would probably require a link on preview.hex.pm to the file on GitHub. Which would also solve it, although adding this extra step.
