### ISSUE TITLE
Search does not include specs

### ISSUE THREAD

**Issue by michallepicki** [elixir-lang/ex_doc#1388]
Currently [searching for trap_exit](https://hexdocs.pm/elixir/master/search.html?q=trap_exit) does not bring up [Process.flag/2](https://hexdocs.pm/elixir/master/Process.html#flag/2), probably because specs are not used for search. Maybe this could be improved?

**Comment by josevalim** [comment]
I think the actual issue here is that Process.flag does not document all options and instead delegates to Erlang. If it was a pure Elixir function, the possible values would be documented on the function doc. I am skeptical about adding specs, I don't think the work and extra bandwidth is worth it and they may even add to false positives. :)

**Comment by michallepicki** [comment]
It does document them, through specs... But alright.

**Comment by josevalim** [comment]
Let's do this: we will remove all documentation from the Elixir code, we will leave only typespecs. How documented is our code now? :)

What I am saying is, if we were not delegating Erlang, we would have a section describing all options and what they do in the docs themselves. The specs are always auxiliary information.

**Comment by michallepicki** [comment]
I agree, specs alone are not good enough documentation, I just think they could help in cases like the above, indexed with low "weight" - no issue if you think it's a bad idea
