### ISSUE TITLE
Add more colors for easier navigation

### ISSUE THREAD

**Issue by mickel8** [elixir-lang/ex_doc#1577]
Sometimes it's pretty hard for me to navigate through the docs as almost everything is white. Functions, Callbacks, Types, everything in the sidebar looks the same.

What about introducing more colors, something that Rust already does in their documentation.

E.g.

![image](https://user-images.githubusercontent.com/24651552/172012415-dedd3bf5-21f9-4d3c-a617-8991dbc19b97.png)

**Comment by josevalim** [comment]
Hi @mickel8! Can you please provide an example (and/or links) of where Rust uses different colors in the sidebar to help with navigation?

**Comment by mickel8** [comment]
I messed it up, actually they don't do this in the sidebar but in some kind of summary e.g. https://doc.rust-lang.org/std/future/index.html. Things in the sidebar are blue but in the summary, Traits, Structs, Macros have their own colors.

This would correspond to `Summary` section in Elixir docs. I mean this section https://hexdocs.pm/elixir/1.13.4/Regex.html#summary

**Comment by josevalim** [comment]
Oh, it seems they are consistent and separate constructs always appear within those colors in headers and summary (except for the sidebar).

I am not sure how impactful this change would be for Elixir. As a typed language, types are much more pervasive in Rust than Elixir, so you see stuff like `pub fn pending<T>() -> Pending<T>` where `pending` is a function and `Pending` is a type, but those don't appear together in Elixir. Even specs have their own listing in a separate line. So I am not sure how beneficial the change would be because they are always in separate contexts.

It is a neat approach though, so thanks for sharing! I will keep this in mind and see if there are future opportunities where we can apply this! :)
