### ISSUE TITLE
`:skip_undefined_reference_warnings_on` with modules in pages

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/ex_doc#1750]
I have an extra page, say `pages/my-page.md`. In it, I mention `MyModule`, which is now a private module.

I don't want to warn on it. If I pass

```elixir
skip_undefined_reference_warnings_on: ["MyModule"]
```

I still get the warning. The only way I found to silence it is to pass `"pages/my-page.md"` altogether, which is not what I want because it silences all warnings. When I inspected ex_doc, the `config.id` and `config.module_id` were both `nil`.

This might be a documentation problem, or a missing feature, or a bug. Not really sure. I'd love to help out more but I’m a lacking time at the moment 😉

**Comment by wojtekmach** [comment]
Yeah we can silence warnings on a given page which is useful for pages with deprecations like CHANGELOG.md. At the moment we cannot silence particular warnings. I think it might be a useful feature to have. Or, you know, we should be more intentional when we want things to auto link and when we don't (#1663). :)

**Comment by josevalim** [comment]
A PR to add `skip_code_autolink_to: ["Module"]` would be welcome.
