### ISSUE TITLE
Sidebar scroll regression introduced in #1760 (Firefox)

### ISSUE THREAD

**Issue by zachallaun** [elixir-lang/ex_doc#1773]
Hi friends! I noticed a regression in the sidebar behavior in Firefox today. Stepping back through commits and re-building, it looks like it was introduced in #1760.

![image](https://github.com/elixir-lang/ex_doc/assets/503938/8715edbd-8af3-44ee-89ed-cc6e94667562)

**Comment by josevalim** [comment]
I cannot reproduce this. What is your commit? Notice that we have a separate commit for updating the assets, is there any chance that you got a commit before the assets update? You can also try calling `mix build`. :)

**Comment by josevalim** [comment]
I was able to reproduce it here: https://hexdocs.pm/elixir/main/Kernel.html

@angelikatyborska if you have the time, can you please take a look?

**Comment by angelikatyborska** [comment]
Huh, I see! I did not test how the scrollbar looks like when it's overflowing vertically, and it does not look good. I'll try to fix it now.

Posting a screenshot for the record because the original one shows more problems than just the overflow:

![Screenshot 2023-09-15 at 19-46-46 Kernel — Elixir v1 16 0-dev](https://github.com/elixir-lang/ex_doc/assets/7852553/612fe89c-fc41-4f8a-b548-6308cdb50f01)

**Comment by zachallaun** [comment]
Thank you both!
