### ISSUE TITLE
Proposal: link/hover-docs to mix tasks

### ISSUE THREAD

**Issue by zachdaniel** [elixir-lang/ex_doc#1775]
Hello! I think that this can be a relatively simple additive change that involves detecting in code blocks when a mix task is called, and finding the corresponding module. This could work very similar to module autocompletion (since they are modules ultimately). For example:

`mix ash_state_machine.generate_flow_charts --foo bar` could link to the relevant mix task. I'd be happy to put this on my list and give it a shot, if it seems like an interesting addition.

**Comment by wojtekmach** [comment]
I believe we discussed this in the past, that it would be nice to autocomplete more expressions. I think we even mentioned Mix tasks but also, say, if we already link `Foo.bar/1` then we should link `Foo.bar(:bar)` too.

Ultimately we didn't to keep things simple as well as because we have an escape hatch which is do "custom links": ``[text](`code`) ``. We already autolink if you write `` `mix ash_state_machine.generate_flow_charts` ``. So you can do:

```markdown
[`mix ash_state_machine.generate_flow_charts --foo bar`](`mix ash_state_machine.generate_flow_charts`)
```
