### ISSUE TITLE
Text of code block within a info admonition block is barely legible in darkmode

### ISSUE THREAD

**Issue by garazdawi** [elixir-lang/ex_doc#1867]
See https://github.com/erlang/otp/issues/8151 for an example.

Not 100% sure if it is the text or background that should be updated?

**Comment by DavidOliver** [comment]
As the light theme has dark-on-light code, I would think light-on-dark for the dark theme. @josevalim?

**Comment by josevalim** [comment]
@DavidOliver please pull latest and run `mix build`. I have created an example page with all admonition blocks so we can take a look at it in dev.

The issue above only happened if there was no language selected, otherwise we should light on dark, so it was an easy fix. But your feedback on the example page is very welcome.

**Comment by DavidOliver** [comment]
Good good - looks fine to me in the context of the current approach.

I would be up for experimenting with dark admonition block background colours for the dark theme, creating the inverse of the light theme, so that there's less bright tone in general, which I think is what dark theme users tend to prefer, if you'd be interested.

**Comment by josevalim** [comment]
It is up to you. :)

**Comment by DavidOliver** [comment]
Okay. :) I'll have a go at that and submit a PR if I think it's worth considering before looking at #1866.
