### ISSUE TITLE
allow Source links to local destinations

### ISSUE THREAD

**Issue by RichMorin** [elixir-lang/ex_doc#191]
guess_url (ex_doc.ex#L54-L69) seems to be hard-coded to go to only Bitbucket or GitHub.  I'd like to have a way to point to a file system destination (eg, "file:...") on my local machine, or a URL that is accessible on the LAN or WAN.

**Comment by eksperimental** [comment]
Link to the code: https://github.com/elixir-lang/ex_doc/blob/master/lib/ex_doc.ex#L59

We need to have a format for the links that are neither the two repositories mentioned above.
--source-url "http://anothergitserver.com/src/{ref}/{path}#Line{line}"

I think it's safe to use curly brackets because they get encoded in urls, in the unfortunate situation that the url includes {ref}, {path} or {line} as part of the address.

I can implement this solution if you guys are ok with it.

**Comment by whatyouhide** [comment]
@eksperimental seems nice, go for it!

**Comment by josevalim** [comment]
We already support it via `source_url_pattern`. We can automatically inflect the pattern based on source_url or source_ref but in cases we don't, `source_url_pattern` is the way to go!

**Comment by josevalim** [comment]
Maybe this is a documentation issue but the feature is there! :D
