### ISSUE TITLE
Linking (internally) to non-existent function/types

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#192]
you can see in
http://elixir-lang.org/docs/master/elixir/Dict.html
Where it reads "Based on these functions, Dict generates default implementations for the following functions:"
* [get/2](http://elixir-lang.org/docs/master/elixir/Dict.html#get/2)
* [get/3](http://elixir-lang.org/docs/master/elixir/Dict.html#get/3)

funtion [get/2](http://elixir-lang.org/docs/master/elixir/Dict.html#get/2) doesn't exist, but it is still being referenced.
note that the markdown for this code is `get/2`, so it's being autolinks.

what is it is in reality, is a callback: so it should link to : http://elixir-lang.org/docs/master/elixir/Dict.html#c:get/2

But maybe we shouldn't link at all. (get/3 will link to the function, so it's not consistent)
I'm not too sure which logic to follow here.

**Comment by milmazz** [comment]
@josevalim @eksperimental I think this issue is already fix.

After review the [Dict](http://elixir-lang.org/docs/master/elixir/Dict.html) module documentation, in particular this section:

> Based on these functions, Dict generates default implementations for the following functions:
>
> * drop/2
> * equal?/2
> * fetch!/2
> * get/2
> * get/3

`get/2` does not link to a nonexistent function anymore. Also, does not link to the proper [callback](http://elixir-lang.org/docs/master/elixir/Dict.html#c:get/2) (IMHO we should link to the proper callback). But I want to know what do you think of this.

**Comment by ericmj** [comment]
It shouldn't link to the callback unless a callback link is used, maybe `Dict` docs should be changed to use `c:...` links. We should automatically create links for all arities of functions with default arguments though.

**Comment by josevalim** [comment]
#110 is the same issue, except it happens for types.

**Comment by josevalim** [comment]
Yes, docs should be changed instead.
