### ISSUE TITLE
Remove support for application/erlang+html

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#1934]
Instead require users to use Erlang/OTP 27+ from future ExDoc versions.

**Comment by garazdawi** [comment]
Please don’t do this as edoc still generates this format and always will. Infact the edoc docs on erlang.org uses this format to make sure that it still works.

**Comment by josevalim** [comment]
I see, thanks.

Do you think in the long term we will be able to tell `edoc` users they will either have to use `edoc` built-in layout or migrate to Erlang/OTP 27?

**Comment by garazdawi** [comment]
In the long term I hope that edoc usage will become relatively small, so that it can be removed/deprecated. But until that happens I would like exdoc to continue supporting this format. If the maintenance of this backend ends up being an issue there might be things we can do in edoc to make it easier.

**Comment by josevalim** [comment]
We are fine to keep this for now then. :)
