### ISSUE TITLE
displayed URL should reflect web page location

### ISSUE THREAD

**Issue by RichMorin** [elixir-lang/ex_doc#196]
If I go to a new location in the frames-based version of the online documentation (whether by following a link or using the sidebar for navigation), the web page should display the new URL.   For example:

  http://elixir-lang.org/docs/master/elixir/Exception.html#message/1

**Comment by ericmj** [comment]
Can you do that with frames? It's the the subframes URL and the browser will always display the URL of the page that includes the frames.

Maybe if we changed the way we do the frames it would be achieved, but that's a larger undertaking and has other consequences.

**Comment by eksperimental** [comment]
hi @RichMorin, this has in someway already been implemented recently,
it's good when you need to link from other pages
your link will be:
http://elixir-lang.org/docs/master/elixir/#!Exception.html#message/1

just add #! and then the name of the file, and it will take you there,
the reason why you cannot update the url in the address bar is because of security reaons that a child frame cannot update the url of its parent (the window in this case)

there are [plans to get rid of frames](https://github.com/elixir-lang/ex_doc/issues/175), and i think that's at the top of the list for my priorities on working on this project.

**Comment by ericmj** [comment]
Getting rid of frames is the proper fix, thanks for working on it.
