### ISSUE TITLE
Show sidebar menu open

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#231]
One thing that I miss from the old version with frames is that we could navigate through the sidebar menu and we will still be positioned and the current page will be highlighted in blue,
I think it will be a good idea if the sidebar menu could already be positioned according to the page being loaded.

The tricky part is when we are accessing a module that is going past down the first page, how can we show that as we load the page,
and as we cannot set cookies under file:// it's impossible to maintain the state (position and additional modules opened)

Thanks

**Comment by ericmj** [comment]
Another issue with the new version is that searches are lost when navigating the menu.

**Comment by eksperimental** [comment]
@ericmj true. that's really bad ;-(

**Comment by josevalim** [comment]
@eksperimental this should be fixable because every page knows which module it is showing, so we could just highlight it in the menu.

@ericmj and this can be fixed by adding a ?search=foo for all links once there is a search. Then, on page load, we check the query string and properly update the search field.

**Comment by eksperimental** [comment]
@josevalim I know the problem is then you are viewing  a module that is way down the list,

**Comment by josevalim** [comment]
Adding the info here to the other issue.
