### ISSUE TITLE
Sidebar does not scroll on elixir master docs

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#242]
This is due to our latest changes.

See: http://elixir-lang.org/docs/master/elixir/

/cc @milmazz

**Comment by milmazz** [comment]
@josevalim The scroll is working (I just checked on Chrome and IE), or at least I think is the expected behavior with the [Affix](http://getbootstrap.com/javascript/#affix) component from Bootstrap. 

![bootstrap-affix](https://cloud.githubusercontent.com/assets/34700/8876747/42cd1062-31e7-11e5-8c72-738ce89296d0.gif)

Or are you referring to something like the [stable docs](http://elixir-lang.org/docs/stable/elixir/)?, where you can scroll the sidebar regardless of the content position.

**Comment by josevalim** [comment]
Yes, you can just scroll at the end of the page. Since Kernel is huge, people will be confused and won't be unable to scroll the sidebar. So I was thinking something like before or something that scrolls from the beginning (and not the end). Thoughts?

**Comment by milmazz** [comment]
@josevalim I agree, in some cases (like Kernel) is confusing as you mentioned. So, let me look into that and I'll try to fix it.
