### ISSUE TITLE
CMD + link clicking problematic behavior

### ISSUE THREAD

**Issue by benwilson512** [elixir-lang/ex_doc#388]
Using: Chrome 45, OS X 10.10

To reproduce:
- Do a search
- CMD click one of the results

Result:
Initially the browser warns of a popup, and the results page suddenly ends up back at the top of Kernel.

After allowing popups, the above steps will indeed open the clicked upon link (after some delay) but the search page is relocated to Kernel.

**Comment by Dignifiedquire** [comment]
Not sure how we can fix this, `Right Click + Open in new tab` does not produce the issue, I'm afraid Chrome is doing something really strange con Cmd click here :disappointed:

**Comment by eksperimental** [comment]
the same issue happens here  in Chrome in Linux, with CTRL + click
or middle button click.

It does not happen with RIGHT CLICK + OPEN IN NEW TAB

**Comment by josevalim** [comment]
I have good news and bad news. The good news is that this no longer exists in master and CMD-click properly opens in another tab. The bad news is that clicking on the link with CMD is closing the search results but they should be kept open.

I am hoping these bad news are actually good news because they should be easy to fix (although I personally have no idea how :smile:).

**Comment by josevalim** [comment]
Please ignore me. I was using safari. :(

**Comment by benwilson512** [comment]
Thanks! I know this had to be a weird one to find.
