### ISSUE TITLE
[Mobile] Link icon overlaps with hamburger

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#434]
This only happens in mobile.

![img_20150920_141459](https://cloud.githubusercontent.com/assets/9133420/10095753/52a0e0be-6396-11e5-804d-d9fe56ac4d22.jpg)

**Comment by eksperimental** [comment]
Here's another example, with the title of the section.

![img_20150925_150854](https://cloud.githubusercontent.com/assets/9133420/10095947/b037979e-6397-11e5-8e8e-74bdab39ae11.jpg)

**Comment by eksperimental** [comment]
Happening here (on a desktop computer)
https://hexdocs.pm/phoenix_html/Phoenix.HTML.html
![ex_doc_burger](https://cloud.githubusercontent.com/assets/9133420/10134954/48975be0-6614-11e5-92fb-c31d94b25bbe.png)

maybe we could make the burger have it in a circle with a purple bacground with an translucid background.. so if something goes under it, we can still see what's behind, and you can still see the icon. now because both are while, the icon and the title, they blend in.

**Comment by nscyclone** [comment]
If I am not mistaken, anchors appear before the headers only on hover. To be honest, I am not sure that they are necessary because the action for both anchor and header is the same. The simpler the better.
![Regular](https://cloud.githubusercontent.com/assets/5345029/19310999/4e279104-9095-11e6-98d6-45741bcf2ef3.png)
![Hover](https://cloud.githubusercontent.com/assets/5345029/19311000/4e35df20-9095-11e6-8456-ede98562d8e5.png)
According to the desktop hamburger issue I'd like to suggest adding: `word-break: break-all;` to `.sidebar-projectName`. Also the mentioned `.sidebar-projectName` selector has a `max-width: 155px;` for some unknown reason. I suppose this value is not big enough and must be increased with taking margins, paddings and hamburger width into account. The result could look like this:
![example](https://cloud.githubusercontent.com/assets/5345029/19311681/10bd8078-9098-11e6-9d43-98584f9f1c21.png)

**Comment by josevalim** [comment]
> According to the desktop hamburger issue I'd like to suggest adding: word-break: break-all; to .sidebar-projectName. Also the mentioned .sidebar-projectName selector has a max-width: 155px; for some unknown reason. I suppose this value is not big enough and must be increased with taking margins, paddings and hamburger width into account. The result could look like this:

Can you please send a PR for that?

**Comment by aphillipo** [comment]
I've personally always found the Anchor symbol a little weird.  Shall we just remove it and them this bug can be closed :-)?

Also there is obviously no hover on real mobile devices so maybe we are worrying about something that will only affect a very very limited number of situations?

**Comment by josevalim** [comment]
Yes, I am fine to leave this as is.
