### ISSUE TITLE
[Search] Support CTRL+(ENTER/Click)

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#533]
It has happened to me many times that typing the full name of a function in the search box, to get a result page, and end up clicking on the first result.
I would LOVE to have a feature that when hit ENTER or clicked the magnifying glass icon in combination with the CONTROL key, it will directly redirect me to the first match.

something that would mimic what we have in IEx, when you use the `h` command without specifying its arity. 

One thing to add would be that if a function matches exactly the ones in kernel, it should take me to that one function. For instance, if 

The rules for redirecting would be in this order of precedence:
- if the search string matches exactly a module name, it redirects directly.
- if no module was given, and "search string" exactly matches a function name in Kernel or Kernel.SpecialForms, directly redirect (example: search for `puts` redirects to `Kernel.inspect/2`)
- if the search only returned one result it will automatically redirect the user.
- if the search returned more than one result, but all functions belong to the same module and differ only in arity, redirect to the function with the smallest arity.
-  if more than one result is returned, do not redirect, and display the search results.

How does the idea sound to you guys?

**Comment by michalwarda** [comment]
I can take this one. Will start it today. 

- [ ] Differentiate search functionality when searching with CTRL key pressed - _Redirect Search_
- [ ] When _Redirect Search_ is active (CTRL is down) change the color of magnifying glass near search input to inform about different search functionality
- [ ] Somehow inform user of the possibility of using _Redirect Search_.
- [ ] _Redirect Search_ that exactly matches `module` name redirects directly to it
- [ ] _Redirect Search_ that exactly matches `Kernel` or `Kernel.SpecialForms` function redirects to it
- [ ] _Redirect Search_ returning 1 `result` redirects directly to it
- [ ] _Redirect Search_ returning more than 1 `function` but differing only in arity redirects to the `function` with lowest arity
- [x] Otherwise _Redirect Search_ shows search `results` just like on normal search

I hope I didn't misunderstand anything here.

**Comment by eksperimental** [comment]
Yes thats exactly what i mean. We should correct something though.
"Kernel or Kernel.SpecialForms" should be when the project is the elixir language, when its a different project it should be the main module, usually the one with the same name as the project

**Comment by josevalim** [comment]
If someone would like to implement it, please go ahead. Maybe instead of using the search, we could have something more like editors or GitHub's `Ctrl+T`, where you enter a special prompt to go to a single file or function. This would be, in my opinion, a more robust API than something that feels like Google's I'm feeling lucky.

**Comment by aphillipo** [comment]
I like the idea of Autocomplete as you type for this and might take it at some point.  What entities should be part of the search just function/macro names and arity?  Or do we want structs and callables and signals and behaviours as well?

**Comment by josevalim** [comment]
@aphillipo I think everything that we can possibly search should work (module names, function, macros, structs, etc).

**Comment by aphillipo** [comment]
@josevalim I have a prototype of search browser  history that works (still a few weird edge cases to iron out).  I’ll refector search to support this afterwards.  I have one question though, which shortcut should we use?

**Comment by aphillipo** [comment]
Ctrl + T on Mac I guess?  Presumably Ctrl + T on Windows/Linux opens a new tab?

**Comment by aphillipo** [comment]
Be good to be able to effectively Alt - Tab between history items from with ExDoc too.  Probably a different feature though.

**Comment by josevalim** [comment]
Thanks Andrew!

Is it a simple shortcut for the search? i think so right? Since if we need
autocomplete we could also add it directly there. If so, any shortcut is
fine by me. What do sites usually use? Alternatively we can simply start
with the search bar focused.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by aphillipo** [comment]
@josevalim I was thinking it would look like Spotlight on a Mac instead, with a nice shadow and as you typed it would show search results?

**Comment by josevalim** [comment]
Oh, I see. So one is a "Go to" kind of thing, the other is an actual search. Yes, that sounds good to me then. If we are going to pick a shortcut, I would use "t" which is the file finder for github.

**Comment by aphillipo** [comment]
"t" with no modifier key works!  Please try out the history in #748 !

**Comment by aphillipo** [comment]
Oh I can add the Ctrl search/Go to feature as well but I'll be based on the history changes.  It's very quick but it should probably be based upon #749 to avoid issues.  Do we need an autocomplete Spotlight style search as well?

**Comment by josevalim** [comment]
@aphillipo I think we are discussing two things:

1. Search history with autocomplete based on the history
2. A feature that works like go-to in auditors

Is it correct? I think both would be welcome, I just want to make sure we don't talk past each other.

**Comment by aphillipo** [comment]
Yes. I believe this issue is 2. - shall I open an issue for 1.?

**Comment by josevalim** [comment]
No, it is fine. I just wanted to make sure we were on the same page.

**Comment by josevalim** [comment]
Closing in favor of #965
