### ISSUE TITLE
Back and forward does not work for fragment links

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ex_doc#593]
When clicking a link to a function on the same page the back and forward does not work in the browser for that link.

**Comment by josevalim** [comment]
Is that something that we broke (because browsers support it) or is that something we need to support ourselves?

**Comment by ericmj** [comment]
I think it's something we broke. Compare clicking a fragment link (next to a header) on https://github.com/elixir-lang/ex_doc and on https://hexdocs.pm/ecto/Ecto.Repo.html. On github I can use back and forward to jump between headers, but with ex_doc the back button does not work.

**Comment by josevalim** [comment]
This has been fixed but unfortunately it means we can no longer animate once the sidebar is clicked. 

The reasoning is written on the commit message. I tried to find an alternative so we still keep the scrolling animation but failed to do so. Since having the back button working is more important than the animation, we won't have scrolling until someone can add it back without breaking Chrome.
