### ISSUE TITLE
Sigil syntax highlighting

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/ex_doc#658]
Hello, I noticed syntax highlighting for sigils is somewhat irregular (e.g. left bracket is highlighted differently from right one):

![zrzut ekranu 2017-01-06 o 22 31 25](https://cloud.githubusercontent.com/assets/76071/21733781/91e82458-d460-11e6-8d55-92b3098525f8.png)

I'd like to propose to change it to either:

1.
![zrzut ekranu 2017-01-06 o 22 31 51](https://cloud.githubusercontent.com/assets/76071/21733797/9c819f66-d460-11e6-86c3-a516794226ef.png)

2. 
![zrzut ekranu 2017-01-06 o 22 34 16](https://cloud.githubusercontent.com/assets/76071/21733802/a06939f4-d460-11e6-8cd5-d75b64e923d7.png)

What do you think?

Edit: oh and yet another option would be to highlight everything inside sigil (including `-`) with the same color

**Comment by josevalim** [comment]
I think we simply depend on a javascript library to do syntax highlighting. So that would need to be solved there first. :)

**Comment by wojtekmach** [comment]
Good point, it's not an issue on ex_doc then.

Btw, I'm curious, do you have a preference? fwiw in iex the entire sigil is printed with the same color.

**Comment by eksperimental** [comment]
yes, it has to do with highlight.js project.
I have submitted this bug (i think it's the same, but it was reported with `~S`) almost two years ago, but it looks like it hasn't been fixed yet.
https://github.com/isagalaev/highlight.js/issues/730

by the way, we should update the package to the latest version c9.9.0, 
since we are running v8.8.0
and see if the problem is still there.
