### ISSUE TITLE
[Mobile] Sidebar disappears  when clicked in search box

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#736]
This is happening in Chrome browser for Android, in hexdocs.pm

**Comment by josevalim** [comment]
Which URL precisely? And can you please post a screenshot? :)

**Comment by nscyclone** [comment]
@josevalim I suppose any URL would work, for example, https://hexdocs.pm/ecto. I was unable to reproduce in any of the desktop browsers, but it reproduces on Android in Chrome 58.0.3029, Firefox 53 and Opera Mini 25.0.2254. Unfortunately, I don't have any Apple devices to confirm that the bug is present there as well.
It should not be related to responsive layout because changing the viewport size on desktop makes no effect. The only thing that comes in mind is `touch` events but I [don't remember](https://github.com/elixir-lang/ex_doc/search?utf8=✓&q=touch) any explicit usage of them in `ex_doc`.

**Comment by aphillipo** [comment]
It works fine on iOS (10.3.2) if that's helpful.

**Comment by eksperimental** [comment]
Correct. It happens in any URL, in landscape and portrait view

**Comment by eksperimental** [comment]
And a screenshot wouldnt work, as it dissapears instantly as if you were closing thr side panel

**Comment by aphillipo** [comment]
Might be worth taking a photo of a live phone then to at least everyone would be able to see it?

**Comment by eksperimental** [comment]
The change is instant. if you want a before is the with sidebar open, ADN the after is wi not side bar.
you can only see that recording a screencast.

**Comment by profil** [comment]
Browsers running on android will trigger the `resize` event when the on-screen keyboard pops up. Since the `initialize` function in `assets/js/sidebar.js` adds a listener on window resize, the sidebar will be closed every time a resize happens.

I guess the solution would be to either remove the event listener on window resize, or only close the sidebar if the width changed (ignoring the height).

**Comment by nscyclone** [comment]
Huge thanks to everyone. I suppose that #742 should fix the issue.

**Comment by eksperimental** [comment]
Thank you @nscyclone for fixing this issue.
Amazing work!

**Comment by eksperimental** [comment]
@josevalim I think we need to make a new release as this is a very annoying bug if you are checking docs in a mobile
