### ISSUE TITLE
Add markdown engine callbacks

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#786]
In the markdown module:

 * `def assets(format), do: [{basename1, contents1}, {basename2, contents2}, ...]`
 * `def before_closing_head_tag(format), do: ~S(<link rel="stylesheet" ...>)`
 * `def before_closing_body_tag(format), do: ~S(<script ...></script>)`

Rationale described here: #784

**Comment by tmbb** [comment]
Ok, a question. Do you want this to be a formal behaviour? Something like this (you'll probably object to the use of `defoverridable`, but I still have to read about the more modern alternatives that landed in elixir 1.4)

```
defmodule ExDoc.MarkdownProcessor do
  @callback assets(atom) :: [{String.t, String.t}]
  @callback before_closing_head_tag(atom) :: String.t
  @callback before_closing_body_tag(atom) :: String.t

  defmacro __using__(_params) do
    quote do
      # The "official" implementations will `use` the default implementation.
      # We shouldn't modularize the JS right now because highlight.jsis a useful fallback for 
      # languages other than Elixir
      @behaviour ExDoc.MarkdownProcessor

      def assets(:html), do: []
      def assets(:epub), do: []
      
      def before_closing_head_tag(:html), do: ""
      def before_closing_head_tag(:epub), do: ""
      
      def before_closing_body_tag(:html), do: ""
      def before_closing_body_tag(:epub), do: ""

      defoverridable [
        assets: 1,
        before_closing_head_tag: 1,
        before_closing_body_tag: 1
      ]
    end
  end
end
```

To be able to use this behaviour from an external module like `makedown`, I have to depend on `ex_doc`. This means that `makedown` can't be used to document `ex_doc` (you get some nasty cyclic dependencies). I have two solutions for this:

1. Implement the behaviour on `makedown` without using `@behaviour ExDoc.MakedownProcessor`
2. Add `makedown` as an optional dependency to `ex_doc` and implement the behaviour there.

These solutions are effectively equivalent. The only difference is that the second one gives us the warm fuzzy feeling of having an actual Behaviour at the cost of a little more coupling, right? What do you think?

Other than that, the implementation is very easy, wrote it in about 10mins (still no tests, those will take longer).

**Comment by tmbb** [comment]
Related question (it's related to makeup/makedown buy I ask it here because it related to those packages as seem by the ex_doc user):

Currently, to use makedown with ex_doc, the user needs to add 3 lines to the mix.exs file:

1. Select `Makedown.ExDoc` as the markdown processor
2. Add `makedown` as a dependency
3. Add `makeup_elixir` as a dependency

The last line in particular seems very arbitrary and is confusing (remember, it was confusing to you)... We could cut it to two lines by getting rid of the need to declare `makeup_elixir` as a dependency. There are two ways to do it:

1. Declare `makeup_elixir` as a  `makedown` dependency, risking longer compile times for a module that might not be needed for some users or

2. Create a new "virtual" package named something like `makedown_ex_doc` which imports both `makedown` and `makeup_elixir` and does nothing of its own. This adds a layer of indirection between dependencies, which is not ideal, but since it doesn't actually include new code, it might be acceptable.

What do you think of these solutions?

**Comment by josevalim** [comment]
Let's define a formal behaviour and no code-generation please. It is three simple functions that returns empty lists and empty strings.

The virtual package can be an interesting venue to pursue if you don't want to have logic specific to ExDoc, such as the `before_closing_head_tag` and `before_closing_body_tag` discussed in this thread, in your `makedown` package. This way `makedown_ex_doc` can then even depend on `ex_doc` and declare the proper behaviours. So to me it sounds like an avenue worth pursuing.

If one day we make `ex_doc` depend directly on `makedown` then `makedown_ex_doc` will no longer be necessary.

**Comment by tmbb** [comment]
> Let's define a formal behaviour and no code-generation please. It is three simple functions that returns empty lists and empty strings.

Ok, I've defined a formal behaviour which is now implemented in all "officially" supported markdown implementations (no code generation, of course):

```elixir
defmodule ExDoc.MarkdownProcessor do
  @callback assets(atom) :: [{String.t, String.t}]
  @callback before_closing_head_tag(atom) :: String.t
  @callback before_closing_body_tag(atom) :: String.t
  # had forgotten about this one yesterday lol
  @callback to_html(String.t, Keyword.t) :: String.t
end
```

I just need to add some tests and then I'll send a PR.

> The virtual package can be an interesting venue to pursue if you don't want to have logic specific to ExDoc [...]  This way `makedown_ex_doc` can then even depend on `ex_doc` and declare the proper behaviours

I've done this too, although the package is called `ex_doc_makedown`. It's not an `ex_doc` addon to `makedown`, it's a `makedown` addon to `ex_doc`. `ex_doc` is the *foundation* on top of which you use `makedown` (See? A makeup joke. They practically write themselves).

Actually `ex_doc_makedown` doesn't even depend on `makedown` anymore. I've duplicated some code to make it easier to keep the same API even as `makedown` gains capabilities. The scope of `ex_doc_makedown` is intentionally more limited and my first priority is to make it easy to use at the cost of extensibility.

It's interesting, because now that `ex_doc_makedown` depends on `ex_doc` you don't even have to include `ex_doc` anymore (it looks like `ex_doc_makedown` is doing all the work). You still have to set the markdown processor, though. This *might* be avoided with some kind of black magic with `@after_compile` to set the `:markdown_processor` option from inside `ex_doc_makedown` but I don't know if it's such a good idea. The problem with black magic is that you start by doing some compile-time dependency injection and before you know it you end up summoning Cthulhu from the Elder Dimensions Beyond The Void or something like that...

When I make up my mind about a decent extensibility mechanism for `makeup` and `makedown` I might merge the code base again. As of now, `ex_doc_makeup` (still unreleased) will be kept simple, supid and optimized to be used with `ex_doc`.

**Comment by tmbb** [comment]
> If one day we make ex_doc depend directly on makedown then makedown_ex_doc will no longer be necessary.

Sure, it's literally 1 file of elixir code + one file with CSS (the CSS can be included inline in the Elixir source, but it's ugly)

**Comment by josevalim** [comment]
>  This might be avoided with some kind of black magic with @after_compile to set the :markdown_processor option from inside ex_doc_makedown but I don't know if it's such a good idea.

It isn't. :) And `@after_compile` would trigger only during compilation, so it wouldn't stick. Plus, we should keep it simple and all that.

I like the name `ex_doc_makedown` (or `ex_doc_makeup`, you used both :P). The only important thing to have in mind is that you cannot define modules in the `ExDoc` namespace. So do not define `ExDoc.Makedown` or similar because otherwise we will have conflicts if we ever merge it into ExDoc. `ExDocMakedown` or `MakeDown.whatever` is fine though.

Before publishing `ex_doc_makeup`, can you please link to the repo? Maybe we can add it into ExDoc now but I am afraid you may want to move things faster for now and adding it to ExDoc won't help on that front.

**Comment by tmbb** [comment]
> I like the name ex_doc_makedown (or ex_doc_makeup, you used both :P)

Sorry, it's meant to be `ex_doc_makeup` (I can see people typosquatting on `ex_doc_makeup`, maybe I should register a dummy?).

> The only important thing to have in mind is that you cannot define modules in the ExDoc namespace.

Sure, the package defines only one module named `ExDocMakedown`.

> Before publishing ex_doc_makeup, can you please link to the repo?

Sure, I'll link it so you can give your opinion. 

> Maybe we can add it into ExDoc now but I am afraid you may want to move things faster for now and adding it to ExDoc won't help on that front

Let me work on it alone for a while. I'm still not sure on how to make it extensible (i.e. how to allow the user to use custom lexers). I'll tell you when I'm confident enough with the API for it to be incorporated into ExDoc.

**Comment by josevalim** [comment]
> Sorry, it's meant to be ex_doc_makeup 

If you already have a repo, just push your bare version for now.

> Sure, the package defines only one module named ExDocMakedown.

Shouldn't it be `ExDocMakeup`? :P

**Comment by tmbb** [comment]
> Sorry, it's meant to be ex_doc_makeup

Sorry, I'm typing and thinking too quickly. It's meant to be `ex_doc_makedown`. On the other hand, I'm making this mistake too many times. Maybe I should call it `ex_doc_makeup`? It's more intuitive: ExDocs + makeup syntax highlighting. But it's a markdown implementation, so it should be makedown -.-

I don't know. Help me here... `ex_doc_makeup` or `ex_doc_makedown`? Now I'm leaning towards `ex_doc_makeup`...

**Comment by tmbb** [comment]
The repository is here: https://github.com/tmbb/ex_doc_makeup

It doesn't work as it is now because it requires my as of yet private version of `ex_doc` that does something with the behaviour.

**Comment by josevalim** [comment]
@tmbb cool, i dropped some comments but otherwise it looks good to go!
