### ISSUE TITLE
Titles (or module names) in the sidebar should by hyperlinks to the respective file

### ISSUE THREAD

**Issue by tmbb** [elixir-lang/ex_doc#791]
Quite often, when navigating some project's docs I have to click on the module name, then "Top", and only then I'm redirected to the module I want. This means that the default thing I want to do, which is visiting a module, takes two clicks instead of one. I think the module name should be a hyperlink that redirected to the page.

This removes a little flexibility (you can't click the module name and be redirected to the Exceptions, for example), but It doesn't really decrease the number of clicks. You can always redirect to teh right page right away, and if the user wants to go to a specific section they can always click the opened links in the sidebar.

I rarely use those links in the sidebar anyway, as I prefer to search for the text with the Browser's search feature.

**Comment by josevalim** [comment]
This is how it worked before and we got a lot of complaints that it was impossible to navigate the sidebar without changing from the current page, so we do not plan to revert to that, as it will only cause folks that reported issues in the past to report them again.

**Comment by OvermindDL1** [comment]
Any chance of having that chainlink icon appear to the right of the module names then?  I'd happily click that to go straight to the file instead of multiple very-irritating clicks.  ^.^

Currently I open every-single-module in a new tab by middle-clicking the module name instead of just navigating in one tab because of this, it's faster to click once on a tab to go between modules then it is click multiple times to go between modules (having to move the mouse in between).  >.>

**Comment by josevalim** [comment]
> Any chance of having that chainlink icon appear to the right of the module names when hovered then?

Yup, totally fine with that. We proposed it in the past but nobody worked in a PR. :)
