### ISSUE TITLE
Possible to stream generation? -- running out of ram :(

### ISSUE THREAD

**Issue by DarkMarmot** [elixir-lang/ex_doc#865]
My current project uses macro generated modules that map to external file format specs.

This results in about 2000 modules -- and while I can compile about 200 of them with 7GB of ram for the process, the whole project consumes all of my memory, swap space, etc. and pretty much hangs....

(The ability to group and hide in the menu would also be pretty awesome).

Thanks,
Scott S.

**Comment by josevalim** [comment]
I believe the issue is the unbound concurrency that we have in master. If
you look at ExUnit.Formatter.HTML, you will see that we have two places we
call Task.async+await.

Can you please try removing those calls in favor of a single Enum.map/2
with the Task.await content? Once you do, does it improve the memory
consumption?

If it does improve, the actual fix would be really simple.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by michalmuskala** [comment]
Should we switch to using `Task.async_stream`?

**Comment by josevalim** [comment]
That was the plan but we never did it so we support older Elixir versions.
But we do plan to require v1.7 in the near future so we should use it soon.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by DarkMarmot** [comment]
Thanks for the quick help! :)

I tried changing to Enum.map and doing a deps.compile -- I did eventually get my documentation output, though it took about 10-15 minutes and and memory usage for the process hovered around 20GB -- which just seems pretty high.

**Comment by josevalim** [comment]
@DarkMarmot we can probably make it increase up to 3-4 minutes, depending on the number of cores, but there isn't much we can do regarding the memory usage since we do need to load all modules and documentation in memory for things like linking and cross references.

Using modules like that in Elixir is pretty unconventional and it is likely that you will run into other issues further down the road. You may consider using `record` or simply maps to model this data, since they don't require full modules. We will try to improve ExDoc but ultimately there is no guarantee we can comfortably support your app.

**Comment by DarkMarmot** [comment]
@josevalim I totally understand, thanks again for the help and consideration! 

The reason for module generation was primarily in order to get in-editor code completion.
The project involves parsing and supporting HL7 medical messages across multiple versions. 

Common practice in the industry is to address almost everything by ordinal position (which is hard to read and document).

If curious, you can see the unconventional implementation at:
https://github.com/HCA-Healthcare/elixir-hl7

Note: I'm relatively new to Elixir, but really love it so far 👍 

I will probably just add notes in the documentation for usage for now.

**Comment by josevalim** [comment]
Glad to hear you are enjoying it!

[Records](http://hexdocs.pm/elixir/Record.html) would allow you to model those as well with compile time guarantees, although they are only compile time structs and not polymorphic (i.e. you can't implement protocols for them). But given the sheer amount of data, it may be worthy a try.

Alternatively, if the spec has multiple areas, you could define multiple projects, one for each area and have a parent project with all subprojects. This is what the GoogleCouldPlatform does for their APIs: https://github.com/GoogleCloudPlatform/elixir-google-api/

**Comment by OvermindDL1** [comment]
> Records would allow you to model those as well with compile time guarantees, although they are only compile time structs and not polymorphic (i.e. you can't implement protocols for them). But given the sheer amount of data, it may be worthy a try.

Well if necessary my [ProtocolEx](https://hex.pm/packages/protocol_ex) library can as it is built on matchers and thus works fine with Records, though I'm curious how it would handle such a massive project, I've never tried to stress it with so many modules but it does have a few obvious compile-time performance enhancements that I could do (runtime is basically as efficient as you can get with you even able to control the matching order if necessary for fine-tuning)...

As for the file format specs, definitely using a tagged-tuple/record sounds like a far better idea as a single module could handle it all (though separating them into more modules is definitely better for usability)...

This is an interesting problem to talk about on the Elixir Forums though.  :-)

**Comment by josevalim** [comment]
I have pushed improvements to master but they will require Elixir v1.7 which still has not been launched. In a week we should have a RC out and a new ex_doc release so you can try it out. Other improvements are welcome but not our focus since this is a very corner case. Thanks!
