### ISSUE TITLE
Update build to use Webpack instead of Gulp

### ISSUE THREAD

**Issue by skbolton** [elixir-lang/ex_doc#873]
A conversation was started over on phoenixframework/phoenix#2949 about getting this project updated to Webpack. I would love to tackle this. Is the goal to simply replace the current gulp tasks or is there other changes that would like to get mad

**Comment by josevalim** [comment]
Hi @skbolton! I think we can do this in two steps:

1. First update our current webpack usage to a more recent version of webpack

2. Then see if we can replace our current gulp tasks by webpack too

I would recommend to first get started with 1, have a PR reviewed and merged, and then we can tackle 2. Thoughts?

**Comment by yordis** [comment]
@skbolton Have you done anything here?

@josevalim aside this, are you willing to move to SASS?
- Community support: more people are familiar with it
- Speed: C++ implementation
- The same anyway but better

**Comment by yordis** [comment]
Also worth to mention that I went to this route already https://github.com/yordis/ex_doc/tree/feature/webpack

Details like code-splitting the highlight.js package because it is not friendly to modern bundlers (there is an issue open in the Github repo about it)

And the naming on how you output the files in the `dist` folder (for example, fonts are only inside the html version, I moved it into the Webpack build) will make a little hard to convert everything to Webpack.

That is not quite done, missing to make it pass the testing (probably add another webpack for use `null-loader` for the assets)

**Comment by josevalim** [comment]
I don't see a reason to move to SASS. Speed is not a bottleneck here and we are only using basic features that most people familiar with CSS can grasp without worries.

**Comment by skbolton** [comment]
@yordis I was going to do a rough first pass which just gets the current pipeline up to webpack 4. I am pretty much done with that. @josevalim mentioned after that moving to replace all of gulp. At that point I figured I would worry about optimizations.
