### ISSUE TITLE
Proposal: Include README, CHANGELOGS, etc. to the generated documentation

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#924]
There is information that is crucial that is being left out in the docs.

In the case of Elixir core, if users are Installing Elixir from a package and not having access to the source code, they cannot know for example of recently (soft) deprecated functions or even the install instructions.

For other packages, it can be the same situation, including the LICENSING information.

I think we need to device a way to either opt-in or opt-out to include these files.
Please let me know if we should move the discussion to Elixir forum if you think it should get more feedback

**Comment by wojtekmach** [comment]
I like this idea.

We can already opt-in by setting: `extras: ["README.md"]` like e.g. Decimal does: https://hexdocs.pm/decimal/readme.html

We have a somewhat related issue https://github.com/hexpm/hexpm/issues/560 where we discuss displaying README right on the package landing page, maybe instead of rendering README there we'd display a link to HexDocs.pm/package/readme.html instead? What's nice about potentially using ExDoc for this is we already have markdown rendering, assets hosting, auto linking etc. Here's how it could look like:

![screenshot 2018-11-11 at 06 51 25](https://user-images.githubusercontent.com/76071/48309594-5042df80-e57e-11e8-9d41-091b0c7e45d7.png)

---

Note: "Online documentation", "README", "CHANGELOG" links would be automatically created by Hex.pm (like docs link one currently does), and only "GitHub" link would come from package metadata.

And here are examples of CHANGELOGs rendered: http://wojtekmach.pl/hexdocs/decimal/1.5.0/changelog.html, http://wojtekmach.pl/hexdocs/elixir/master/changelog.html.

Coming back to https://github.com/hexpm/hexpm/issues/560, maybe rendering README, CHANGELOG etc is an interim step to rendering them on hex.pm? It's a bit hacky buy maybe we could embed HexDocs.pm/decimal/readme.html in an iframe and remove ExDoc layout via css.

cc @ericmj

**Comment by josevalim** [comment]
This is totally possible today and each project can opt-in if they want to by adding it to extras. I don't think we should do it by default. For example, many projects have a short README that only link to the docs, this is duplicate information. Other projects do host the README as landing page. If we want more projects to do this, then we can change some of our examples to include those by default. :+1:
