### ISSUE TITLE
Provide "Search or go to..." functionality

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#967]
The functionality should mirror the "search or jump to" functionality on GitHub.

Once the user types "foobar" in the search box, the first entry will be "Search foobar..." but below we will show any existing matching entry:

```
 |-----------------------------------|
 | -> | to_charlist                  |
 |-----------------------------------|
 | Search to_charlist...             |
 | Atom.to_charlist/1 (function)     |
 | Kernel.to_charlist/1 (function)   |
 | List.to_charlist/1 (function)     |
 | CharList (module)                 |
 |-----------------------------------|
```

As we press up and down, we can choose the search or to go straight to a given entry. Note this autocomplete functionality is exactly how the search works today, so we can likely just reuse the inner logic.

I am also aware we may need to change how the search is styled today or even move it elsewhere completely. Suggestions on this area are welcome.

Extra: to improve the usability we also should: provide shortcuts to all entries in the top right of the sidebar. For example, pressing s should start "Search". Pressing "c" should "Collapse/expand". And pressing "n" should toggle "Night/day mode".

**Comment by eksperimental** [comment]
I really like the way this issue was solved. Here are my comments.

First, if you move over your mouse horizontally, it looks like it is all the same link, the module title, and the arrow. I think we need to make a distinction, and change the color or do something to the arrow so when you hover it, it is clear they are two different things.

Secondly, I would change to "Go to" title to something more descriptive, like: "Go to module documentation" or something else, no particular preference here.

**Comment by eksperimental** [comment]
I opened it here, since in the new issue, I think it is more oriented to the search feature. Let me know if I should move it there

**Comment by josevalim** [comment]
This issue is about the search functionality. :) The issue about the
feature you are talking about was closed. Perhaps we should open up a new
issue with your comments as feedback? We can call it “feedback about goto
functionality in sidebar”, as I assume others will have more feedback when
we role it out more. Thanks!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by archdragon** [comment]
I've created a quick prototype to get a better sense of how this feature might work - I think it might be a good starting point to get the conversation going :)

![image](http://krowinski.com/ex_doc/autocomplete.gif)

## Demo
➡️ [Example generated with Elixir repo](http://krowinski.com/ex_doc/autocomplete_demo)


## Summary

I think this feature can work well with existing search and page layout.

I imagine it as an autocomplete that appears in the sidebar - immediately after you start typing.

![image](https://user-images.githubusercontent.com/1810732/53687535-10bf1f80-3d36-11e9-83de-4ceeec0e8ec6.png)

Since the sidebar space is limited and some function/module names can be quite long I've decided to display the result type underneath the result name, instead of aligning it to the right:

![image](https://user-images.githubusercontent.com/1810732/53687289-3bf43f80-3d33-11e9-8d4d-a313a17d72ef.png)

Right now, for functions, I moved the module name to the subtitle/description section. For modules it just shows the `Module` subtitle.

I'm not happy with it yet and still experimenting with ideas. Maybe something like:

```
Map
module

map/2
function in enum
```

to clearly and explicitly mark functions as functions. Or maybe different icons for functions and modules?

(I also I need to add some special rules for `exceptions` and `tasks` right now they both will be displayed with the `module` tag.)

When it comes to the code - demo uses existing search functionality and filters/sorts results differently.

## Keyboard Shortcuts

Since keyboard shortcuts are not coupled with search, I've decided to create a separate PR for them. :)

https://github.com/elixir-lang/ex_doc/pull/976

## Crazy ideas for the future versions

### Short description/snippets
I've seen that we were thinking about extracting short snippets/descriptions (ie. in https://github.com/elixir-lang/ex_doc/issues/971 ). If, in the future, we have access to things like that we can even display the snippets right in the search ie:

![image](https://user-images.githubusercontent.com/1810732/53687428-ce491300-3d34-11e9-9441-74b83a81f314.png)

I've even started experimenting with this, using json generated by the https://github.com/elixir-lang/ex_doc/pull/974

Quick (and quite broken) prototype here: http://krowinski.com/ex_doc/autocomplete_snippets_demo/readme.html :)

It's also possible for results to overflow the sidebar, if we really need some extra space (ie. for snippets/tags):

![image](https://user-images.githubusercontent.com/1810732/53687505-90002380-3d35-11e9-923d-44e3113a3490.png)

**Comment by josevalim** [comment]
Closing in favor of PR #985.
