### ISSUE TITLE
Anchor links are broken

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#978]
They only work when they are internal links. 
Try the search and click in any result.

ExDoc is unusable with this bug!

Found in Chromium and Firefox

**Comment by josevalim** [comment]
Can you please provide more information? Is it in master? Released code?
How did you try it? Which app? I have no idea how to start looking into
this.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by eksperimental** [comment]
It's in master, and with the Elixir documentation

**Comment by josevalim** [comment]
Where did you click? Which anchor links? In the sidebar? Or in the content?

**Comment by eksperimental** [comment]
in the contents of the search.

**Comment by josevalim** [comment]
I still cannot reproduce it.

**Comment by josevalim** [comment]
Can you please describe precisely what you are searching, what you are clicking and what are you expecting to happen? As members of the ExDoc team we should really be giving  better examples of bug reports. :)

**Comment by eksperimental** [comment]
Sorry, I didn't write a deep report, because it seems to obvious. You cannot click anywhere, it will take you to the top of the page. It takes only 1 minute using ExDoc to be annoyed by it.

On the other hand I said "Try the search and click in any result" with that given information, you find the bug. If you cannot reproduce it, that's a different story

**Comment by josevalim** [comment]
It is not obvious. I searched for the letter "a", clicked on the first result, and everything looked OK because I was taken to the page and I could see the function head I clicked on.

Also, because you said ExDoc became unusable, I was expecting nothing to work *at all*, so once the link actually sent me to the page, it seemed ok.

The bug only became apparent once I clicked a definition that would take me to the bottom of the page and noticed that it didn't scroll.

If you spent 30 seconds more on the report it would have saved me 5 minutes or more.
