### ISSUE TITLE
Allow autocomplete (old search) to find by Mod.fun

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#986]

**Comment by archdragon** [comment]
Few notes about this behaviour:

Old search returns all function names if the module name matches the search term. By looking at what is highlighted we can tell if the result actually matches or if it was included only, because it belongs to the matching module.
![image](https://user-images.githubusercontent.com/1810732/55040842-8616cb00-502a-11e9-9a59-26f8ac1cac13.png)


"Old search" can find the function by the "Module.function" term. The problem is that such term is not being highlighted at all.
![image](https://user-images.githubusercontent.com/1810732/55040864-a5adf380-502a-11e9-8c3d-abd9ff813e48.png)

Since old search functions (`findIn`, `findNested`) are not being used by the new search anymore (and now belong to the autocomplete) I can rewrite them to include only the matching terms - and even directly provide the structure we need for autocomplete. This would reduce the code complexity and remove the need for additional data transformations.

**Comment by josevalim** [comment]
@archdragon yes, please go ahead with the refactoring and this feature then as part of the existing pull request, since it will simplify the code. :D

**Comment by archdragon** [comment]
On it! :)

**Comment by archdragon** [comment]
I've updated the search today - `Module.function` now finds results as expected.

When the search term looks like "Module.function", I've decided to only highlight the function/callback/type name, since the full module name is already displayed in the suggestion description/subtitle:

![image](https://user-images.githubusercontent.com/1810732/55117572-a0fd4400-50eb-11e9-91a3-c70d50e6636a.png)

I've uploaded a demo here: [ [demo](http://krowinski.com/ex_doc/autocomplete_mod_fun/Kernel.html) ]
