### ISSUE TITLE
Autocomplete mix tasks

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/ex_doc#994]
Currently it isn't clear that a suggestion is a Mix task:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/76071/55625582-812fe500-57a9-11e9-9186-59c3b4848d5c.png">

We should add a label "(Mix task)" or ideally instead prepend a "mix " so it shows up as:

* "mix compile"
* "mix compile.app"

etc.

If we do the latter though, should we also be able to search by "mix comp"?

cc @archdragon @josevalim

**Comment by archdragon** [comment]
> We should add a label "(Mix task)" or ideally instead prepend a "mix " so it shows up as:
> 
> "mix compile"
> "mix compile.app"


👍 

That's clear and simple to add. If we decide to go with this, then I think we need to handle the "mix" prefix in search terms. (ie. both "comp" and "mix comp" should return the "compile" task as a result)

**Comment by josevalim** [comment]
I like the "mix " prefix because it means we can type `"mix a"` to get autocomplete for mix tasks.

I am also wondering if we should instead fix on the Elixir side of things and make the name of the item "mix ..." in the sidebar. This means we get this for free. The sidebar for Elixir would look like this:

![image](https://user-images.githubusercontent.com/9582/55628571-5c3f7000-57b1-11e9-8c45-22b4f5deebec.png)

**Comment by wojtekmach** [comment]
@josevalim good idea, I'm on it.

**Comment by wojtekmach** [comment]
Closing in favour of a PR.
